---
- name: Init vagrant server
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
  roles:
    - user
    - packages
    # - autocomplete
    # - keys
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform
